67
telminov/ansible-manager pull request #68
Opened 2017-07-03 16:03 UTC by YraganTron

2017-07-03 16:16 UTC, YraganTron commented on core/models.py
> +    repeat_iter = models.IntegerField(default=-1)
Добавление поля для отслеживания пауз между запусками. Скорее всего это все же нужно хранить в базе, но в темплейте ли?  С практической точки зрения это кажется удобнее всего, но вот правильно ли это с логической, тут у меня сомненье.

2017-07-03 16:16 UTC, YraganTron commented on core/views/task_template.py
> +class RepeatTask(mixins.PermissionRequiredMixin, views.FormView):
Здесь наследуюсь от FormView и скорее всего это тоже не лучшая идея.

2017-07-03 16:16 UTC, YraganTron commented on core/datatools/cron.py
> +    def repeat_task(self):
Непосредственно сам повторный запуск реализован в кроне. Думаю это логичнее т.к. здесь мы имеем sleep(60) и запуск этот происходит в автоматическом режиме

2017-07-03 16:16 UTC, YraganTron commented on core/datatools/tasks.py
> +    def calculate_repeat_iter(template):
Часть логики также отошла в TaskManager(Наверно тоже не есть хорошо, что это все раздробилось). Это нужно для отслеживания поле repeat_iter, нам нужно менять значения после успешных тасков и пофейленных.

2017-07-05 15:05 UTC, YraganTron commented on core/models.py
> +class RepeatTask(models.Model):
RepeatSetting

2017-07-06 05:48 UTC, telminov requested changes

2017-07-06 05:48 UTC, telminov commented on core/datatools/repeat.py
> +class Repeat:
Давай и файл, и класс перерименуем из repeat в fail_repeat (FailRepeat), чтобы подчеркнуть, что мы пытаемся повторять именно по фейленные.

2017-07-06 05:48 UTC, telminov commented on core/datatools/repeat.py
> +        templates_task = models.TaskTemplate.objects.filter(repeat_task__isnull=False).distinct()
templates_task -> template_tasks

2017-07-06 05:48 UTC, telminov commented on core/datatools/repeat.py
> +            self.run_repeat_task()
run_repeat_task -> process_fails

2017-07-06 05:48 UTC, telminov commented on core/models.py
> +    repeat_number = models.IntegerField(null=True)
null убери, сделай default=0

2017-07-06 05:48 UTC, telminov commented on core/datatools/repeat.py
> +            if last_task.repeat_number:
last_task.repeat_number по дефолту должен быть 0, тогда этот блок логики не понадобится

2017-07-06 05:48 UTC, telminov commented on core/models.py
> +    template = models.ForeignKey(TaskTemplate, related_name='repeat_task')
related_name='repeat_task' -> related_name='repeat_settings'

2017-07-06 05:48 UTC, telminov commented on core/datatools/repeat.py
> +            repeat_queryset = models.RepeatSetting.objects.filter(template=template)
эта строка не нужна, потому что ты можешь обратиться template.repeat_settings.count()

2017-07-06 05:48 UTC, telminov commented on core/datatools/repeat.py
> +            if repeat_number < repeat_queryset.count():
сделай лучше 
```python
if repeat_number > repeat_queryset.count():
    continue
```

2017-07-06 05:48 UTC, telminov commented on core/datatools/repeat.py
> +                time_repeat = last_task.dc + datetime.timedelta(minutes=repeat_queryset[repeat_number].pause)
задачи бываю долгие (например восстановление базы из бекапа - 40 минут). Пэтому лучше брать не last_task.dc, а что-то типа last_task.logs.last().dc

2017-07-06 05:48 UTC, telminov commented on core/models.py
> +    is_created_automatically = models.BooleanField(default=False)
is_created_automatically -> is_automatically_created

2017-07-06 05:48 UTC, telminov commented on core/views/task_template.py
> +    template_name = 'core/task_template/RepeatSetting.html'
core/task_template/RepeatSetting.html -> core/task_template/repeat_setting.html

2017-07-06 05:48 UTC, telminov commented on core/views/task_template.py
> +    title = 'Repeat Setting'
title = 'Repeat Setting' -> title = 'Repeat Settings'

2017-07-06 05:48 UTC, telminov commented on supervisor/prod.conf
> +[program:repeat_task]
repeat_task -> fail_repeat

2017-07-06 05:48 UTC, telminov commented on supervisor/prod.conf
> +command = python3 manage.py repeat_task
python3 manage.py repeat_task -> python3 manage.py fail_repeat

2017-07-06 19:31 UTC, telminov requested changes

2017-07-06 19:31 UTC, telminov commented on core/datatools/fail_repeat.py
> +class FailRepeat:
FailRepeat -> FailRepeater

2017-07-06 19:31 UTC, telminov commented on core/management/commands/fail_repeat.py
> +            scheduler = FailRepeat()
scheduler -> repeater

2017-07-06 19:31 UTC, telminov commented on core/views/task_template.py
> +repeat_task = RepeatSetting.as_view()
repeat_task -> repeat_settings

2017-07-06 19:31 UTC, telminov commented on core/urls.py
> +    url(r'^task_templates/(?P<pk>\d+)/repeat/$', task_template.repeat_task, name='task_template_repeat'),
repeat -> repeat_settings
task_template.repeat_task -> task_template.repeat_settings
task_template_repeat -> task_template_repeat_settings

2017-07-06 19:31 UTC, telminov commented on core/views/task_template.py
> +class RepeatSetting(mixins.PermissionRequiredMixin, views.FormView):
RepeatSetting -> RepeatSettings (в отличии от модели, во вьюхе идет управление несколькими настройками - формсетом)

2017-07-07 16:45 UTC, merged