#76 пофиксил баг
telminov/ansible-manager pull request #78
Opened 2017-09-05 19:14 UTC by YraganTron

2017-09-06 08:22 UTC, telminov requested changes

2017-09-06 08:22 UTC, telminov commented on core/static/core/js/variables.coffee
> -    correctedIds()
выглядит стремно

2017-09-06 08:22 UTC, telminov commented on core/views/task_template.py
> +    copy_template = False
А давай создадим отдельную вьюху для копирования. И не будем смешивать редактирование с копированием.

2017-09-06 08:39 UTC, YraganTron commented on core/views/task_template.py
> +    copy_template = False
Может стоит тогда везде разделить создание и редактирование объектов, а то коряво будет смотреться.

2017-09-06 08:39 UTC, YraganTron commented on core/static/core/js/variables.coffee
> -    correctedIds()
Эта функция каждый раз при добавлении нового элемента расставляла значения у форм от 0 до n-1. Если мы удаляем форму, то у нас она перемещается в отдельное место и её номер сохраняется. Т.е. после удаления пары существующих форм, мы захотим добавить пару своих форм, заполним их, а на стороне сервера их невозможно будет принять т.к. у нас будет удаленная форма с таким же номером, как и наша существующая.

2017-09-13 04:54 UTC, telminov requested changes

2017-09-13 04:54 UTC, telminov commented on core/views/task_template.py
> +    formset_model = models.Variable
зачем?

2017-09-20 07:12 UTC, merged